# logging:
#   level:
#     ROOT: INFO
#     org.springframework: ERROR
#     org.hibernate: ERROR
#     com.kgisl.spring.spring: ALL
  
#   pattern:
#     console: "- %msg%n"
#     file: "*[%-5p]-- %m--%n"
#   file: logs/spring.log
  
# server:
#   port: 8080

